# Generated by Django 6.0.2 on 2026-03-02 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('user_agent', models.TextField(blank=True)),
                ('podcast_app', models.CharField(blank=True, max_length=100)),
                ('bytes_served', models.BigIntegerField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='channels.channel')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='episodes.episode')),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['episode', 'timestamp'], name='analytics_e_episode_5be27e_idx'), models.Index(fields=['channel', 'timestamp'], name='analytics_e_channel_193e63_idx'), models.Index(fields=['timestamp'], name='analytics_e_timesta_47536d_idx')],
            },
        ),
    ]
