# Generated by Django 6.0.2 on 2026-03-02 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_channel_id', models.CharField(max_length=255, unique=True)),
                ('channel_title', models.CharField(max_length=500)),
                ('channel_description', models.TextField(blank=True)),
                ('channel_thumbnail_url', models.URLField(blank=True)),
                ('youtube_uploads_playlist_id', models.CharField(blank=True, max_length=255)),
                ('podcast_title', models.CharField(blank=True, max_length=500)),
                ('podcast_description', models.TextField(blank=True)),
                ('artwork_url', models.URLField(blank=True)),
                ('rss_slug', models.SlugField(max_length=255, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(default='Technology', max_length=100)),
                ('explicit', models.BooleanField(default=False)),
                ('episode_prefix', models.TextField(blank=True)),
                ('episode_suffix', models.TextField(blank=True)),
                ('filter_config', models.JSONField(default=dict)),
                ('monitoring_active', models.BooleanField(default=True)),
                ('websub_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('websub_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_video_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['-created_at'],
            },
        ),
    ]
