# Generated by Django 6.0.2 on 2026-03-02 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polar_order_id', models.CharField(max_length=255, unique=True)),
                ('polar_product_id', models.CharField(max_length=255)),
                ('polar_customer_id', models.CharField(max_length=255)),
                ('amount_cents', models.IntegerField()),
                ('tax_amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('billing_reason', models.CharField(blank=True, max_length=100)),
                ('invoice_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polar_subscription_id', models.CharField(max_length=255, unique=True)),
                ('polar_customer_id', models.CharField(max_length=255)),
                ('polar_product_id', models.CharField(max_length=255)),
                ('polar_price_id', models.CharField(max_length=255)),
                ('plan_tier', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
