# Generated by Django 6.0.2 on 2026-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creator_groups_creator_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='display_name',
        ),
        migrations.AddField(
            model_name='creator',
            name='username',
            field=models.CharField(default='username', max_length=255),
            preserve_default=False,
        ),
    ]
