# Generated by Django 6.0.2 on 2026-03-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_creator_display_name_creator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
