# Generated by Django 6.0.2 on 2026-03-02 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple', 'Apple Podcasts'), ('amazon', 'Amazon Music'), ('google', 'Google Podcasts'), ('pocket_casts', 'Pocket Casts')], max_length=50)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('feed_url', models.URLField(blank=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='channels.channel')),
            ],
            options={
                'db_table': 'podcast_directories',
                'unique_together': {('channel', 'platform')},
            },
        ),
    ]
