# Generated by Django 6.0.2 on 2026-03-02 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(max_length=50, unique=True)),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('youtube_pub_date', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('youtube_chapters', models.JSONField(default=list)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_s3_key', models.CharField(blank=True, max_length=500)),
                ('audio_size_bytes', models.BigIntegerField(default=0)),
                ('audio_format', models.CharField(default='mp3', max_length=10)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField()),
                ('transcript_url', models.URLField(blank=True)),
                ('download_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='channels.channel')),
            ],
            options={
                'db_table': 'episodes',
                'ordering': ['-pub_date'],
            },
        ),
    ]
